### ISSUE TITLE
Empty PDF

### ISSUE THREAD

**Issue by multim366** [ItaiAviad/Kotar_Downloader#1]
Hi, trying to use the script on Chrome after loading the pages returns a pdf with an empty blank page. Can you help please?
Thanks in advance

**Comment by ItaiAviad** [comment]
Hi! Thank you for you reply issue. It seems that the problem is with CORS on the Kotar website. A possible and easy solution that worked for me is **running Chrome with web security disabled**.

To run Chrome with web security disabled you can go to "chrome://version/" in Chrome, and look at the value of "Profile Path". The path you need is the parent directory of the "Profile Path" value.
For example:
Profile Path:	"/home/username/.config/google-chrome/Default"
So the directory you need is: "/home/username/.config/google-chrome/"
(I am on Linux Operating System. On Windows it would look a bit different, but the same concept should apply).

This is what I used on Linux:
Run Chrome from the command line with: `<chrome-exe> --disable-web-security --user-data-dir="/home/username/.config/google-chrome/"`

On Windows it should be the same. Just put the path to the Chrome `.exe` file in place of the `<chrome-exe>`.
To find the Chrome `.exe` file you should check: [Google Chrome Path in Windows 10](https://stackoverflow.com/questions/40674914/google-chrome-path-in-windows-10)


After opening Chrome with the above methods, try running the script the same way you did before (as described in the README).

Note:
You shouldn't run Chrome with the above flags for everyday activities.

If this solution doesn't work for you, please feel free to reach out again and describe the problem.

Itai

**Comment by multim366** [comment]
It works! Thank you so much for the quick solution.
